version: "3.8"
services:

  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/frontend"
    ports:
      - "3000:3000"
    command: sh -c "npm rebuild esbuild && yarn start"

  backend:
    build: ./backend
    environment:
      - IMDB_KEY=${IMDB_KEY}
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - "./backend:/backend"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
