name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build multi-arch images, tag, and push image to Dockerhub
        
        run: |
          docker buildx create --use

          docker buildx build ./frontend \
            --platform linux/arm64/v8,linux/amd64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/armada-frontend:latest \
            --push

          docker buildx build ./backend \
            --platform linux/arm64/v8,linux/amd64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/armada-backend:latest \
            --push
